@API_PORT = 8003
@API_TOKEN = 4|WJMgQaU18b06kELJefV4WKWoNjy08EIYzQXiGSQNe5c40ac6


### Login
POST http://localhost:{{API_PORT}}/api/ambassador/login
Content-Type: application/json

{
    "email": "ansley.fahey@example.org",
    "password": "password"
}

### Logout
POST http://localhost:{{API_PORT}}/api/ambassador/logout
Content-Type: application/json
Authorization: Bearer {{API_TOKEN}}

### Register
POST http://localhost:{{API_PORT}}/api/ambassador/register
Content-Type: application/json
Authorization: Bearer {{API_TOKEN}}

{
    "first_name": "Joshua",
    "last_name": "Doe",
    "email": "joshua@doe.com",
    "password": "12345678",
    "password_confirm": "12345678",
    "is_admin": 0
}

### Get user
GET http://localhost:{{API_PORT}}/api/ambassador/user
Content-Type: application/json
Authorization: Bearer {{API_TOKEN}}

### Get products (frontend)
GET http://localhost:{{API_PORT}}/api/ambassador/products/frontend
Content-Type: application/json
Authorization: Bearer {{API_TOKEN}}

### Get products (backend)
GET http://localhost:{{API_PORT}}/api/ambassador/products/backend?sort=desc
Content-Type: application/json
Authorization: Bearer {{API_TOKEN}}
