@API_PORT = 8000

### Register
POST http://localhost:{{API_PORT}}/api/admin/register
Content-Type: application/json

{
    "first_name": "John",
    "second_name": "Doe",
    "email": "john@doe.com",
    "password": "12345678",
    "password_confirm": "12345678"
}

### Login
POST http://localhost:{{API_PORT}}/api/admin/login
Content-Type: application/json

{
    "email": "john@doe.com",
    "password": "12345678"
}

### Get user
GET http://localhost:{{API_PORT}}/api/admin/user
Content-Type: application/json
Authorization: Bearer 7|7MITbFkgQx94R09uwGcj9u1OLgKBwgCUps9I4tFa4e5e3180

### Logout
POST http://localhost:{{API_PORT}}/api/admin/logout
Content-Type: application/json

### Update user info
POST http://localhost:{{API_PORT}}/api/admin/users/info
Content-Type: application/json
Authorization: Bearer 5|7CJJJTQgvfaZ4JGVRsmAEFd2m5YZQv7lVNYhevIM1ib498e64a

{
    "first_name": "Doe",
    "second_name": "John",
    "email": "doe@john.com"
}

### Update user password
POST http://localhost:{{API_PORT}}/api/admin/users/password
Content-Type: application/json
Authorization: Bearer 3|7CDbB23WWD9VXhG1u8Dpuhok8tYWDtYIoEwqA3uB8Le141349a

{
    "password": "12345678",
    "password_confirm": "12345678"
}
