@API_PORT = 8000

### Login a user
POST http://localhost:{{API_PORT}}/api/login
Content-Type: application/json

{
    "email": "jane@example.com",
    "password": "123"
}

### Register a user
POST http://localhost:{{API_PORT}}/api/register
Content-Type: application/json

{
    "first_name": "Jane",
    "last_name": "Doe",
    "email": "jane@example.com",
    "password": "123",
    "password_confirmation": "123",
    "role_id": 2
}
