@API_PORT = 8000
@TOKEN = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIzIiwianRpIjoiMWI1Njk1YzFmZDJkNDFmMDFlNGFkY2I3YTQ5YWNmN2YyMjBjYzc5YzBmZDVlZDgzMGNmOWE4NmRmN2NkMTA1OWUyMDM1NDVkMWNkY2MzODMiLCJpYXQiOjE3Mjk5NzE5NzMuNjg5OTMzLCJuYmYiOjE3Mjk5NzE5NzMuNjg5OTM4LCJleHAiOjE3NjE1MDc5NzMuNTU0ODkzLCJzdWIiOiIyMSIsInNjb3BlcyI6W119.jtAy1S5O9HfUxQZLGLz9grKECSZfr2QQrH9qrp3fJZp5KAPJnmbbv7s8YA-htMW53xhL0CcgEwXs6pSOVCCVXr7ph8eZTvlyrQW4Sfh48xkX77fXU9_6JJXV2a8Vjt5O3sN4xVyWnEleBCg4ELDi7aC4BZ7H8waFUqSAu3vNs5uJssn5l4mHMKJMpjFgUVN7HyOLT4HulaWkj32m9cn1L4FBKniGasLYAzClnYi6paX8xJIMgBZZ6yGvmMbAc1mDt6O-dOoNb3YiiNxMcfzdF0NEltMtscnCegPbPbMKQOOtMT9X7jcgjcyxFix9vjJQBgWLKro9R09fOqofJUA0Ucy_2zHGJa6Nm_79PncXNMQj897-fM3f352xZQ0zjFMR9PiD_KnK-Xc9-XqmtURNVfIPjfzvZtK8TI1u3wH8Ba6LwWl1e-a7XoVB26xbl0Ok83hyp_RZWtwlGmx6qlJsYDvvvfMH9yQ5UgUkVpmqgDh1Ly6hXKxI2UZS45lZJJYqh5lDeWJxE0De8bsOxm-PsmvpkbluSiv5AkB-ykIMAfvNzsTOXiGVc3tytQcEkU3f5fze-Sx-sCeWcIk-iJ5MJ5XgM9N17G3FgV924OtuO7LVb2xeAxFuURvpSXOmipmcXGbWvTkdxfXM8xlaO-gwsYgWyQn0jpxYuLm3s-IAB9I
@ROLE_ID = 1

### Get all roles
GET http://localhost:{{API_PORT}}/api/roles
Authorization: Bearer {{TOKEN}}

### Create a role
POST http://localhost:{{API_PORT}}/api/roles
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "name": "Test Role"
}

### Get a role
GET http://localhost:{{API_PORT}}/api/roles/{{ROLE_ID}}
Authorization: Bearer {{TOKEN}}

### Update a role
PUT http://localhost:{{API_PORT}}/api/roles/{{ROLE_ID}}
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "name": "admin"
}

### Delete a role
DELETE http://localhost:{{API_PORT}}/api/roles/{{ROLE_ID}}
Authorization: Bearer {{TOKEN}}
