@API_PORT = 8000
@TOKEN = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIzIiwianRpIjoiOWJlYmYwNmZiMmEyNmU1NWRiZDA0MjYwNDYzM2QwODM0MDNiMTViYzljNzRmZDBjN2QyNjEwMmFlNTdlYmQwZDQxNWE2OTg1YTc0MjFlZDgiLCJpYXQiOjE3Mjk5NTQxNzYuMjgxNTM2LCJuYmYiOjE3Mjk5NTQxNzYuMjgxNTQxLCJleHAiOjE3NjE0OTAxNzYuMTM3Mjk4LCJzdWIiOiIyMSIsInNjb3BlcyI6W119.TMDJPEH3HKDVqDeJ11JCb89XCfXPPuE9gdj_Y_6OR14KncQM6J3ZAE8XAy6SMF1oL0Jpzd_alkwSC31LcVyFysLU4DTU14h4QpKt-nvsLNdierhc-XuYXci7hMnvEJjiSCF-LubiZhU5iPQfr2GcVF87WvFFX1yd42glHbbvPJh3W60plWyyvYn5_n9eZkS8fKQ5zEty5GxO_zQpbBuECXu8encLaeYnb0XRPAU6Ao2gbf1xPvsVukKx9CIlo6aDyba5e3MyWHbJexlu5jj9mgrIcCKtfm4LQjXyDmuzEFEsQ5UrkpP695epK6hNL987ZEFHPLrdV5u17f2jjxCoNjdjkVol5Y9oRYZNFJKgq-TBDPz6porLCBzhFYKTurxp3kBpU5Ym0X9ePGP1fCD5io0jtIZEIabrgiMVslo_qwiIiZ2ntry_l9BQMaBtvc3LAnVjwIg39RWoetXSAF9ZhidyYtvXWkuZjYv8lXgY5fT6ArKzfSzzuEv_yLG4q7bKiH3YsjLUANMrYtshwAW2J1iMelDjrxCHswOAEpqPbVpdHENg8jyL5N4NLSCQ6DmVaPXj6UmDokFrMiy2iUMh6sNngyIV5NAjLFoTE_4xEkbtZJ2fKi61HPjwXPyLW-EuNq8mSZL2kJu_OKkskzY6znwCRcLaDCpHhHcawcb-a60

### Get all users
GET http://localhost:{{API_PORT}}/api/users
Accept: application/json
Authorization: Bearer {{TOKEN}}

### Get a single user
GET http://localhost:8000/api/users/1
Accept: application/json
Authorization: Bearer {{TOKEN}}

### Create a new user
POST http://localhost:8000/api/users
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "first_name": "John",
    "last_name": "Doe",
    "email": "john@example.com",
    "role_id": 1
}

### Update a user
PUT http://localhost:8000/api/users/25
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "first_name": "Jane",
    "last_name": "Doe",
    "email": "jane@example.com",
    "role_id": 2
}

### Delete a user
DELETE http://localhost:8000/api/users/1
Content-Type: application/json
Authorization: Bearer {{TOKEN}}
